= Provisioning a Mobile Client

Prerequisites:

* [x] You have installed Minishift with the mobilecore addon as described in xref:ROOT:minishift_install.inc.adoc[Setting Up].

To provision a mobile client:

. Log into the OpenShift console.
. Click *Add to Project* and choose *Browse Catalog* from the options.
+
You can filter the catalog items to only show mobile specific items by clicking the *Other* tab.
. Choose the mobile client (Android, iOS, Cordova or Xamarin) and follow the wizard for provisioning that client app.

After the mobile client is provisioned, you can navigate to it from Project Overview. This screen dislays a list of mobile services that you can associate with the mobile client and offers to provision any mobile service that is in the service catalog but is not currently provisioned. 

== Related Information

* xref:provisioning-services.adoc[provisioning a mobile service]
* xref:connecting-mobile-clients-to-mobile-services.adoc[associating a mobile client with a mobile service]
